#!/usr/bin/env bash

# ==================================================================
# bb-dotfileslogger
# ==================================================================
# BB-Logger Library File
#
# File:         bb-logger
# Author:       Ragdata
# Date:         15/04/2023
# License:      MIT License
# Copyright:    Copyright © 2023 Darren (Ragdata) Poulton
# ==================================================================
# PREFLIGHT
# ==================================================================
